# Google Bloat
com.google.android.apps.wellbeing
com.google.android.assistant
com.google.android.videos
com.google.android.apps.photos
# System Bloat (Be careful with these)
com.android.chrome
com.google.android.gm
